version: '3.8'

services:
  # 后端服务 (FastAPI)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    container_name: tradingagents-backend
    ports:
      - "8080:8000"
    env_file:
      - ./.env
    volumes:
      - ./tradingagents.db:/app/tradingagents.db
      - ./eval_results:/app/eval_results
    restart: unless-stopped
    networks:
      - tradingagents-network


  # 前端服务 (Nginx 静态托管 + /api 反代后端)
  frontend:
    build:
      context: ./web/frontend
      dockerfile: Dockerfile
    container_name: tradingagents-frontend
    ports:
      - "8000:80"
    env_file:
      - ./.env
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - tradingagents-network

networks:
  tradingagents-network:
    driver: bridge